version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data/
    networks:
      - database_network
    env_file:
      - ./config/environment/.env.db

  backend:
    build: ./backend
    expose:
      - 8000
    networks:
      - database_network
      - nginx_network
    env_file:
      - ./config/environment/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    networks:
      - nginx_network
    env_file:
      - ./config/environment/.env.front
    depends_on:
      - backend

  nginx:
    # build: ./config/nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx/development:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database_data: