name: Deployment back
on:
  push:
    branches:
      - master
jobs:
  deployback:
    name: Deploy backend to EC2
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Hello G19! I SSH into the repo! (:"
            pwd
            cd /home/ubuntu/g19
            pwd
            git pull
            echo "Doing: sudo docker compose stop"
            sudo docker compose stop
            echo "Doing: sudo docker compose build"
            sudo docker compose build
            echo "Doing: sudo docker compose up -d"
            sudo docker compose up -d
            echo "Doing: sudo systemctl daemon-reload"
            sudo systemctl daemon-reload
            echo "Doing: sudo systemctl restart docker"
            sudo systemctl restart docker
