name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deployback:
    name: Deploy backend to EC2
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Hello G19! I SSH into the repo! (:"
            pwd
            cd /home/ubuntu/g19
            pwd
            git pull
            echo "Doing: sudo docker compose stop"
            sudo docker compose stop
            echo "Doing: sudo docker compose build"
            sudo docker compose build
            echo "Doing: sudo docker compose up -d"
            sudo docker compose up -d
            echo "Doing: sudo systemctl daemon-reload"
            sudo systemctl daemon-reload
            echo "Doing: sudo systemctl restart docker"
            sudo systemctl restart docker

  deployfront:
    name: Deploy frontend to S3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      working-directory: ./frontend

    - name: Install
      uses: borales/actions-yarn@v2.3.0
      working-directory: ./frontend
      with:
        cmd: install # will run `yarn install` command

    - name: Build
      uses: borales/actions-yarn@v2.3.0
      working-directory: ./frontend
      with:
        cmd: build # will run `yarn build` command

    # - name: Deploy
    #   uses: borales/actions-yarn@v2.3.0
    #   with:
    #     cmd: deploy # will run `yarn deploy` command

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      working-directory: ./frontend
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Deploy static site to S3 bucket
      working-directory: ./frontend
      run: aws s3 sync ./dist/ s3://iic2173-g19.xyz --delete