name: Upload Vue to S3

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: borales/actions-yarn@v2.3.0
      with:
        run: |
          cmd ls
          cmd cd frontend
          cmd pwd
          cmd install
          cmd build
        # cmd: install # will run `yarn install` command

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public/ s3://iic2173-g19.xyz --delete